### PR TITLE
Code review for calculator.py

### PR DESCRIPTION
**Pull request by JanPoonthong**
So, when you use while loops, make sure that is below is functions, because while loops run the code line by line, and functions are similar but not the same. 

**How functions work?**
You create the functions, inside the functions the code will execute line by line, but only when the functions are called. Look at the tutorial about functions, and how python works line by line. https://www.youtube.com/watch?v=9Os0o3wzS_I
 
**Avoid over indentation level**
Use **PEP 8 -- Style Guide for Python Code**, https://www.python.org/dev/peps/pep-0008/

**If statement**
When you use the if statement, first always remember that you've to start with if, then elif, and else. Not the other way around, you were doing elif, elif, elif, else, _that is wrong_, https://www.youtube.com/watch?v=PqFKRqpHrjw

**Try focusing on the basic first, learn how functions works, indentation, and if statement.**

### CODE REVIEW

**Review by gbowne1 — COMMENTED** [review]
VSCode on Linux did this automatically for me.

**Comment by JanPoonthong** [comment]
You can use .gitignore to ignore the files.

**Review by gbowne1 — COMMENTED** [review]
I will look through this code and do some research on this.

**Comment by JanPoonthong** [comment]
Sure

**Pull request closed without merging**
